output:
  directory: data
  filename: insider
  format: csv

scraping:
  start_year: 2025
  start_month: 5
  max_workers: 5
  retry_attempts: 2
  timeout: 20

filters:
  min_transaction_value: 50000
  transaction_types:
    - P - Purchase
  min_shares_traded: 100
  exclude_companies: []

cache:
  enabled: false
