name: Send Daily Insider Report

on:
  schedule:
    - cron: '30 14 * * *'  # UTC 时间，等于每天 22:30 北京时间
  workflow_dispatch:

jobs:
  insider-report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: python openinsider_scraper.py

    - name: Send email
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: python email_sender.py
